---
- name: Upgrade all packages
  hosts: all
  become: true
  tasks:
    - name: Update APT cache and upgrade all packages
      apt:
        upgrade: dist
        update_cache: yes
        cache_valid_time: 86400
